package modelo1;
// Generated 20-oct-2015 0:07:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * GenPerfil generated by hbm2java
 */
public class GenPerfil  implements java.io.Serializable {


     private Integer genPerfilId;
     private String genPerfilDescripcion;
     private Set genUsuarios = new HashSet(0);
     private Set genPerfilPaginas = new HashSet(0);

    public GenPerfil() {
    }

    public GenPerfil(String genPerfilDescripcion, Set genUsuarios, Set genPerfilPaginas) {
       this.genPerfilDescripcion = genPerfilDescripcion;
       this.genUsuarios = genUsuarios;
       this.genPerfilPaginas = genPerfilPaginas;
    }
   
    public Integer getGenPerfilId() {
        return this.genPerfilId;
    }
    
    public void setGenPerfilId(Integer genPerfilId) {
        this.genPerfilId = genPerfilId;
    }
    public String getGenPerfilDescripcion() {
        return this.genPerfilDescripcion;
    }
    
    public void setGenPerfilDescripcion(String genPerfilDescripcion) {
        this.genPerfilDescripcion = genPerfilDescripcion;
    }
    public Set getGenUsuarios() {
        return this.genUsuarios;
    }
    
    public void setGenUsuarios(Set genUsuarios) {
        this.genUsuarios = genUsuarios;
    }
    public Set getGenPerfilPaginas() {
        return this.genPerfilPaginas;
    }
    
    public void setGenPerfilPaginas(Set genPerfilPaginas) {
        this.genPerfilPaginas = genPerfilPaginas;
    }




}


