package modelo1;
// Generated 20-oct-2015 0:07:50 by Hibernate Tools 3.2.1.GA



/**
 * GenPerfilPaginaId generated by hbm2java
 */
public class GenPerfilPaginaId  implements java.io.Serializable {


     private int genPaginaGenPaginaId;
     private int genPerfilPaginaId;

    public GenPerfilPaginaId() {
    }

    public GenPerfilPaginaId(int genPaginaGenPaginaId, int genPerfilPaginaId) {
       this.genPaginaGenPaginaId = genPaginaGenPaginaId;
       this.genPerfilPaginaId = genPerfilPaginaId;
    }
   
    public int getGenPaginaGenPaginaId() {
        return this.genPaginaGenPaginaId;
    }
    
    public void setGenPaginaGenPaginaId(int genPaginaGenPaginaId) {
        this.genPaginaGenPaginaId = genPaginaGenPaginaId;
    }
    public int getGenPerfilPaginaId() {
        return this.genPerfilPaginaId;
    }
    
    public void setGenPerfilPaginaId(int genPerfilPaginaId) {
        this.genPerfilPaginaId = genPerfilPaginaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GenPerfilPaginaId) ) return false;
		 GenPerfilPaginaId castOther = ( GenPerfilPaginaId ) other; 
         
		 return (this.getGenPaginaGenPaginaId()==castOther.getGenPaginaGenPaginaId())
 && (this.getGenPerfilPaginaId()==castOther.getGenPerfilPaginaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGenPaginaGenPaginaId();
         result = 37 * result + this.getGenPerfilPaginaId();
         return result;
   }   


}


