package modelo1;
// Generated 20-oct-2015 0:07:50 by Hibernate Tools 3.2.1.GA



/**
 * GenPerfilPagina generated by hbm2java
 */
public class GenPerfilPagina  implements java.io.Serializable {


     private GenPerfilPaginaId id;
     private GenPerfil genPerfil;

    public GenPerfilPagina() {
    }

    public GenPerfilPagina(GenPerfilPaginaId id, GenPerfil genPerfil) {
       this.id = id;
       this.genPerfil = genPerfil;
    }
   
    public GenPerfilPaginaId getId() {
        return this.id;
    }
    
    public void setId(GenPerfilPaginaId id) {
        this.id = id;
    }
    public GenPerfil getGenPerfil() {
        return this.genPerfil;
    }
    
    public void setGenPerfil(GenPerfil genPerfil) {
        this.genPerfil = genPerfil;
    }




}


