package modelo1;
// Generated 20-oct-2015 0:07:50 by Hibernate Tools 3.2.1.GA



/**
 * GenPagina generated by hbm2java
 */
public class GenPagina  implements java.io.Serializable {


     private Integer genPaginaId;
     private String genPaginaDescripcion;
     private String genPaginaUrl;
     private Integer genPaginaEstado;

    public GenPagina() {
    }

    public GenPagina(String genPaginaDescripcion, String genPaginaUrl) {
       this.genPaginaDescripcion = genPaginaDescripcion;
       this.genPaginaUrl = genPaginaUrl;
    }
   
    public Integer getGenPaginaId() {
        return this.genPaginaId;
    }
    
    public void setGenPaginaId(Integer genPaginaId) {
        this.genPaginaId = genPaginaId;
    }
    public String getGenPaginaDescripcion() {
        return this.genPaginaDescripcion;
    }
    
    public void setGenPaginaDescripcion(String genPaginaDescripcion) {
        this.genPaginaDescripcion = genPaginaDescripcion;
    }
    public String getGenPaginaUrl() {
        return this.genPaginaUrl;
    }
    
    public void setGenPaginaUrl(String genPaginaUrl) {
        this.genPaginaUrl = genPaginaUrl;
    }

    public Integer getGenPaginaEstado() {
        return genPaginaEstado;
    }

    public void setGenPaginaEstado(Integer genPaginaEstado) {
        this.genPaginaEstado = genPaginaEstado;
    }




}


