package modelo1;
// Generated 20-oct-2015 0:07:50 by Hibernate Tools 3.2.1.GA



/**
 * GenUsuario generated by hbm2java
 */
public class GenUsuario  implements java.io.Serializable {


     private Integer genUsuarioId;
     private GenPerfil genPerfil;
     private String genUsuarioUsuario;
     private String genUsuarioClave;
     private Integer genUsuarioEstado;

    public GenUsuario() {
    }

	
    public GenUsuario(GenPerfil genPerfil) {
        this.genPerfil = genPerfil;
    }
    public GenUsuario(GenPerfil genPerfil, String genUsuarioUsuario, String genUsuarioClave, Integer genUsuarioEstado) {
       this.genPerfil = genPerfil;
       this.genUsuarioUsuario = genUsuarioUsuario;
       this.genUsuarioClave = genUsuarioClave;
       this.genUsuarioEstado = genUsuarioEstado;
    }
   
    public Integer getGenUsuarioId() {
        return this.genUsuarioId;
    }
    
    public void setGenUsuarioId(Integer genUsuarioId) {
        this.genUsuarioId = genUsuarioId;
    }
    public GenPerfil getGenPerfil() {
        return this.genPerfil;
    }
    
    public void setGenPerfil(GenPerfil genPerfil) {
        this.genPerfil = genPerfil;
    }
    public String getGenUsuarioUsuario() {
        return this.genUsuarioUsuario;
    }
    
    public void setGenUsuarioUsuario(String genUsuarioUsuario) {
        this.genUsuarioUsuario = genUsuarioUsuario;
    }
    public String getGenUsuarioClave() {
        return this.genUsuarioClave;
    }
    
    public void setGenUsuarioClave(String genUsuarioClave) {
        this.genUsuarioClave = genUsuarioClave;
    }
    public Integer getGenUsuarioEstado() {
        return this.genUsuarioEstado;
    }
    
    public void setGenUsuarioEstado(Integer genUsuarioEstado) {
        this.genUsuarioEstado = genUsuarioEstado;
    }




}


